# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PJlH_hBwx43geNK7TK4tWyYZ0HVr2Ecb

# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

**Objectives:**
- List popular languages for Data Science
- List commonly used libraries used by Data Scientists
- Create a tabel of Data Science tools
- Create code lines containing arithmetic expressions

Some of the popular languages that Data Scientists use are:
1. Python
2. R
3. Julia
4. SQL
5. Java

Some of the commonly used libraries used by Data Scientists include:
1. Pandas
2. Numpy
3. Matplotlib

|Data Science Tools  |
|--------------------|
|Jupyter Notebook    |
|RS Studio           |
|Apache Spark        |

###Below are a few examples of evaluating arithmetic expressions in Python
"""

# This a simple arithmetic expression to mutiply then add integers
(3*4)+5

# This will convert 200 minutes to hours by diving by 60
def minutes_to_hours(minutes):
  hours = minutes//60
  minutes_lefting = minutes % 60
  return hours, minutes_lefting

minutes = 200
hours, minutes_lefting = minutes_to_hours(minutes)
print(f"{minutes} minutes is equal {hours} hours and {minutes_lefting} minutes" )

"""##Author
Mônica Máximo da Silva
"""